<?php
/**
 * @category   PSystem
 * @package    PSystem_AjaxQuickCart
 * @author     Pascal System <info@pascalsystem.pl>
 * @version    1.1.3
 * @copyright  Copyright (c) 2013-<?php echo date('Y') ?> Pascal System
 */
?>
<div class="ajaxemptycart">
	<div class="page-title">
		<h1><?php echo $this->__('Shopping Cart is Empty') ?></h1>
	</div>
	<div class="cart-empty">
		<?php echo $this->getMessagesBlock()->getGroupedHtml() ?>
		<p><?php echo $this->__('You have no items in your shopping cart.') ?></p>
		<p><?php echo $this->__('Click <a href="%s">here</a> to continue shopping.', Mage::helper('core')->escapeUrl($this->getContinueShoppingUrl())) ?></p>
	</div>
</div>
